import {
    FIND_PATIENT_ADVANCED_DETAILS_LABEL,
    FIND_PATIENT_BASIC_DETAILS_LABEL,
    FIND_PATIENT_NHS_NUMBER_LABEL,
    FIND_PATIENT_POSTCODE_LABEL,
} from "ncrs-host/FindPatientStrings";

const DEFAULT_PAGE_TITLE = "National Care Records Service";
const ROOT_PAGE_TITLE = " - " + DEFAULT_PAGE_TITLE;

export const NHS_NUMBER_SEARCH_TITLE =
    FIND_PATIENT_NHS_NUMBER_LABEL + ROOT_PAGE_TITLE;
export const BASIC_SEARCH_TITLE =
    FIND_PATIENT_BASIC_DETAILS_LABEL + ROOT_PAGE_TITLE;
export const ADVANCED_SEARCH_TITLE =
    FIND_PATIENT_ADVANCED_DETAILS_LABEL + ROOT_PAGE_TITLE;
export const POSTCODE_SEARCH_TITLE =
    FIND_PATIENT_POSTCODE_LABEL + ROOT_PAGE_TITLE;
export const PATIENT_SEARCH_RESULTS_TITLE =
    "Patient search results" + ROOT_PAGE_TITLE;
